export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import NavBar from "@/nav/NavBar";
import "./global.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
